exclude:
    - bootstrap-3.3.5
    - Gemfile
    - Gemfile.lock
    - CNAME
    - assets/images/sources

timezone: Europe/London

highlighter: pygments

navigation:
  - title: The Wedding
    url: /home
  - title: Locations
    url: /locations
  - title: Accommodation
    url: /accommodation
  - title: RSVP
    url: /rsvp

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      title: "Alison & Simon's Wedding"
