exclude:
    - bootstrap-3.3.5
    - Gemfile
    - Gemfile.lock
    - CNAME

timezone: Europe/London

highlighter: pygments

navigation:
  - title: Home
    url: /home
  - title: Times
    url: /times
  - title: Ceremony
    url: /ceremony
  - title: Reception
    url: /reception
  - title: Hotels
    url: /hotels
  - title: Directions
    url: /directions
  - title: RSVP
    url: /rsvp

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      title: "Alison & Simon's Wedding"