exclude:
    - bootstrap-3.3.5
    - Gemfile
    - Gemfile.lock
    - CNAME

timezone: Europe/London

highlighter: pygments

defaults:
    -
        scope:
            path: ""
        values:
            layout: default
            title: "Our Wedding!!"